---
language: node_js
node_js:
  - "4"
  - "6"
  - "stable"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  - TEST_FRAMEWORK=ember-cli-qunit
  - TEST_FRAMEWORK=ember-cli-mocha

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

install:
  - npm install
  - ./bin/install-test-framework.sh

script:
  - npm run lint:js
  - npm test

after_script:
  - npm run coverage
